name: Publish to npm branch

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.1

      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prettier the project
        run: |
          npm run lint:prettier

      - name: ESLint the project
        run: |
          npm run lint:eslint

      - name: Build the project
        run: npm run build
        env:
          CI: true

      - name: Prepare publish
        run: |
          mkdir -p publish
          cp -a package.json README.md publish
          cp -a config.schema.json dist publish

      - name: Prepare env.TAG
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: npm
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: Release ${{ env.TAG }}
